spring.application.name=ai-log-analyzer

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-mini


app.log-analysis.max-file-size-bytes=1048576
app.log-analysis.max-prompt-log-length=5000
app.log-analysis.max-fallback-log-length=4000
app.log-analysis.context-before=2
app.log-analysis.context-after=8


logging.file.name=logs/ai-log-analyzer.log
logging.level.root=INFO
logging.level.com.rahul.ailoganalyzer=DEBUG